### ISSUE TITLE
Proposal: add mouuii to Maintainers

### ISSUE THREAD

**Issue by lyzhang1999** [nocalhost/toc#1]
@mouuii is an engineer at Zadig and his main contributions to Nocalhost are:
1. promoting the use of Nocalhost in Zadig
2. secondary development of Nocalhost and leading the release of the Zadig plugin
3. providing some product ideas

He is personally very interested in Nocalhost and has a good understanding of remote development and is able to help develop Nocalhost further, his responsibilities are mainly:
1. take ownership of the Proposal and lead the community in implementing features
2. drive improvements to Nocalhost in terms of functionality and product
3. participate in the evangelisation of Nocalhost and make Nocalhsot known to the wider community

Therefore, I propose to add mouuii to the Nocalhost Maintainers for a 1 year term.

**Comment by webup** [comment]
/approve

This is really a good move to involve more tech lead level contributors.

**Comment by anurnomeru** [comment]
/approve

dalao!

**Comment by mouuii** [comment]
Thanks , will do my best to make Nocalhost better in a year
